### ISSUE TITLE
need logic for an additional type of constraint on a group

### ISSUE THREAD

**Issue by LoisWriter** [ancientHacker/susen.go#2]
When there are two values that can appear in only two cells of a tile, no other value can be a possibility for those two cells.

**Comment by brotskydotcom** [comment]
This actually applies to any group (row or column or tile), not just tiles.  It's similar to the current "binding" logic, where there is only ONE cell that can contain ONE value, but in this case it applies when there are only TWO cells that can contain TWO values.  And in this case the effect is not to bind the cell but to remove possible values from the cell.

**Comment by brotskydotcom** [comment]
This manifests in the client because it distinguishes between cells that have only one, two, or more possible values.  But in the "one possible value" case it's actually looking at either one possible value or one bound value, whereas in the "two possible values" case it's looking only at two possible values, rather than two "possibly bound" values.  A better approach might be to change the client not to distinguish two from three values, which was also the suggestion of a user.  We might want to only show the "two possible value" case when guiding a required guess (because all bound values have been filled in).

**Comment by brotskydotcom** [comment]
I've moved the user interface to only show green vs. red squares at any given time, where green is what you should work on (smallest number of possibles) and red is what you should not work on.  That makes this issue irrelevant.
